/* 
 * File:   stateMachine.h
 * Author: mateu
 *
 * Created on 12 de Outubro de 2019, 18:15
 */

#ifndef STATEMACHINE_H
#define	STATEMACHINE_H

#ifdef	__cplusplus
extern "C" {
#endif




#ifdef	__cplusplus
}
#endif

//estados da maquina de Estados

enum {
    STATE_DISPLAY,
    STATE_MENUDISPLAY,
    STATE_MENULINGUAGEM,
    STATE_IDIOMAPT,
    STATE_IDIOMAEN,
    STATE_MENUCONFIGVALORES,
    STATE_CONFIGSENSOR1,
    STATE_CONFIGSENSOR2,
    STATE_VALOR1m,
    STATE_VALOR1M,
    STATE_VALOR2m,
    STATE_VALOR2M,
    STATE_CONFIGTEMPO1,
    STATE_CONFIGTEMPO2,
    STATE_VALORT1,
    STATE_VALORT2,
    STATE_1ATIVO,
    STATE_2ATIVO,
    STATE_ERROV1,
    STATE_ERROV2,
    STATE_ACERTOV1,
    STATE_ACERTOV2,
    STATE_MENUDISPLAYDATAHORA,
    STATE_DISPLAYDATAHORA,
    STATE_MENUCONFIGDATAHORA,
    STATE_CONFIGDATA,
    STATE_CONFIGHORA,
    STATE_VALORDATA,
    STATE_VALORHORA,
    STATE_MENUVALORALRME1,
    STATE_VALORALRMEV1,
    STATE_VALORALRMENV1,
    STATE_MENUVALORALRME2,
    STATE_VALORALRMEV2,
    STATE_VALORALRMENV2,
    STATE_IDLE,
    STATE_FIM
};


#endif	/* STATEMACHINE_H */

